---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app
    author: maruti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        app: result-app
    spec:
      containers:
        - name: result-app-container
          image: dockersamples/examplevotingapp_result
...
