---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-app-container
          image: dockersamples/examplevotingapp_worker
...
