---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app-deployment
  labels:
    app: postgres-app
    author: maruti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      name: postgres-app-pod
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres-app-container
          image: postgres
          env:
            - name: POSTGRES_USER
              value: maruti
            - name: POSTGRES_PASSWORD
              value: maruti123
            - name: POSTGRES_DB
              value: maruti_db
...
