---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment
  labels:
    app: redis-app
    author: maruti
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: redis-app
  template:
    metadata:
      name: redis-app-pod
      labels:
        app: redis-app
    spec:
      containers:
        - name: redids-app-container
          image: redis
...
