---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-deployment
  labels:
    name: voter-app
    author: maruti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      name: vote-app-pod
      labels:
        app: vote-app
    spec:
        containers:
          - name: vote-app-container
            image: dockersamples/examplevotingapp_vote
...
