---
version: '3'
services:
  voting-app:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 8080:80
    deploy:
      replicas: 2

  redis-app:
    image: redis
    ports:
      - 6379:6379
  worker-app:
    image: dockersamples/examplevotingapp_worker

  postgres-app:
    image: postgres
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: maruti
        POSTGRES_USER: maruti
        POSTGRES_DB: maruti
  result-app:
    image: dockersamples/examplevotingapp_result
    ports:
      - 9090:80
    deploy:
     replicas: 2
...

